version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Edge endpoint
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=lambda,cloudformation,apigateway,apigatewayv2,dynamodb,dynamodbstreams,sqs,sns,events,logs,iam,sts,cloudwatch,s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"
volumes:
  localstack-data:
